---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: kotlin-multiplatform
pipelines:
  build:
    workflows:
      android_build: {}
      ios_build: {}
workflows:
  android_build:
    steps:
    - git-clone@8: {}
    - restore-gradle-cache@2: {}
    - activate-build-cache-for-gradle@2: {}
    - android-build@1:
        inputs:
        - project_location: "$PROJECT_ROOT_DIR"
        - module: "$MODULE"
        - variant: "$VARIANT"
    - sign-apk@2:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
  ios_build:
    steps:
    - git-clone@8: {}
    - restore-gradle-cache@2: {}
    - activate-build-cache-for-gradle@2: {}
    - xcode-archive@5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
        - configuration: Release
        - automatic_code_signing: api-key
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
  run_tests:
    steps:
    - git-clone@8: {}
    - restore-gradle-cache@2: {}
    - activate-build-cache-for-gradle@2: {}
    - gradle-unit-test@2:
        inputs:
        - project_root_dir: "$PROJECT_ROOT_DIR"
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
    triggers:
      push:
      - branch: main
      pull_request:
      - source_branch: "*"
meta:
  bitrise.io:
    stack: osx-xcode-edge
    machine_type_id: g2-m1.4core
app:
  envs:
  - PROJECT_ROOT_DIR: "./"
    opts:
      is_expand: false
  - MODULE: composeApp
    opts:
      is_expand: false
  - BITRISE_PROJECT_PATH: "./iosApp/iosApp.xcodeproj"
    opts:
      is_expand: false
  - BITRISE_SCHEME: iosApp
    opts:
      is_expand: false
  - BITRISE_DISTRIBUTION_METHOD: app-store
    opts:
      is_expand: false
