name: Job Setup
description: Sets up Java, Gradle, and caching for optimal build performance

runs:
  using: "composite"
  steps:
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4
