@echo off
REM Dokus Server Installation and Startup Script
REM Supports: Windows 10/11
REM Usage: dokus.bat

setlocal enabledelayedexpansion

REM Banner
echo.
echo ============================================
echo.
echo              DOKUS SERVER
echo     Financial Management Platform
echo.
echo ============================================
echo.

echo [*] Detected: Windows
echo.

REM Check if Docker is installed
echo [1/6] Checking Docker installation...

where docker >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [!] Docker is not installed
    echo.
    set /p INSTALL_DOCKER="Would you like to install Docker Desktop? (y/n): "

    if /i "!INSTALL_DOCKER!"=="y" (
        echo [*] Opening Docker Desktop download page...
        start https://www.docker.com/products/docker-desktop/
        echo.
        echo Please:
        echo   1. Download and install Docker Desktop
        echo   2. Start Docker Desktop
        echo   3. Run this script again
        pause
        exit /b 0
    ) else (
        echo [X] Docker is required to run Dokus
        echo Please install Docker Desktop from: https://docker.com
        pause
        exit /b 1
    )
) else (
    echo [+] Docker is installed
)

REM Check if Docker is running
docker info >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [X] Docker is not running
    echo Please start Docker Desktop and run this script again
    pause
    exit /b 1
)
echo [+] Docker is running

REM Check if Docker Compose is available
docker compose version >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    docker-compose version >nul 2>nul
    if %ERRORLEVEL% NEQ 0 (
        echo [X] Docker Compose not found
        echo Please install Docker Desktop which includes Docker Compose
        pause
        exit /b 1
    )
)
echo [+] Docker Compose is installed
echo.

REM Check for .env file
echo [2/6] Configuring environment...

if not exist ".env" (
    echo [!] .env file not found - let's create one!
    echo.
    echo You can press Enter to accept the defaults ^(recommended for quick start^)
    echo or enter custom values for production deployments.
    echo.

    REM Generate random passwords using PowerShell
    for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..24 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]', '' | Select-Object -First 1" 2^>nul') do set "DB_PASS=%%i"
    for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..24 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]', '' | Select-Object -First 1" 2^>nul') do set "REDIS_PASS=%%i"
    for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..24 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]', '' | Select-Object -First 1" 2^>nul') do set "RABBITMQ_PASS=%%i"
    for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..48 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]', '' | Select-Object -First 1" 2^>nul') do set "JWT_SECRET=%%i"

    REM Fallback if PowerShell failed
    if "!DB_PASS!"=="" set "DB_PASS=changeme-db-%RANDOM%%RANDOM%%RANDOM%"
    if "!REDIS_PASS!"=="" set "REDIS_PASS=changeme-redis-%RANDOM%%RANDOM%%RANDOM%"
    if "!RABBITMQ_PASS!"=="" set "RABBITMQ_PASS=changeme-rabbitmq-%RANDOM%%RANDOM%%RANDOM%"
    if "!JWT_SECRET!"=="" set "JWT_SECRET=changeme-jwt-%RANDOM%%RANDOM%%RANDOM%%RANDOM%%RANDOM%"

    echo ============================================
    echo   Configuration
    echo ============================================
    echo.

    REM Database username
    echo Database username:
    echo Default: dokus
    set /p "INPUT_DB_USERNAME=Value (press Enter for default): "
    if "!INPUT_DB_USERNAME!"=="" (
        set "DB_USERNAME=dokus"
    ) else (
        set "DB_USERNAME=!INPUT_DB_USERNAME!"
    )

    REM Database password
    echo.
    echo Database password:
    echo Default: ^<auto-generated secure password^>
    set /p "INPUT_DB_PASSWORD=Value (press Enter for default): "
    if "!INPUT_DB_PASSWORD!"=="" (
        set "DB_PASSWORD=!DB_PASS!"
    ) else (
        set "DB_PASSWORD=!INPUT_DB_PASSWORD!"
    )

    REM Redis password
    echo.
    echo Redis password:
    echo Default: ^<auto-generated secure password^>
    set /p "INPUT_REDIS_PASSWORD=Value (press Enter for default): "
    if "!INPUT_REDIS_PASSWORD!"=="" (
        set "REDIS_PASSWORD=!REDIS_PASS!"
    ) else (
        set "REDIS_PASSWORD=!INPUT_REDIS_PASSWORD!"
    )

    REM RabbitMQ username
    echo.
    echo RabbitMQ username:
    echo Default: dokus
    set /p "INPUT_RABBITMQ_USERNAME=Value (press Enter for default): "
    if "!INPUT_RABBITMQ_USERNAME!"=="" (
        set "RABBITMQ_USERNAME=dokus"
    ) else (
        set "RABBITMQ_USERNAME=!INPUT_RABBITMQ_USERNAME!"
    )

    REM RabbitMQ password
    echo.
    echo RabbitMQ password:
    echo Default: ^<auto-generated secure password^>
    set /p "INPUT_RABBITMQ_PASSWORD=Value (press Enter for default): "
    if "!INPUT_RABBITMQ_PASSWORD!"=="" (
        set "RABBITMQ_PASSWORD=!RABBITMQ_PASS!"
    ) else (
        set "RABBITMQ_PASSWORD=!INPUT_RABBITMQ_PASSWORD!"
    )

    REM JWT Secret
    echo.
    echo JWT secret (64+ chars):
    echo Default: ^<auto-generated secure password^>
    set /p "INPUT_JWT_SECRET=Value (press Enter for default): "
    if "!INPUT_JWT_SECRET!"=="" (
        set "JWT_SECRET_FINAL=!JWT_SECRET!"
    ) else (
        set "JWT_SECRET_FINAL=!INPUT_JWT_SECRET!"
    )

    REM JWT Issuer
    echo.
    echo JWT issuer:
    echo Default: https://dokus.local
    set /p "INPUT_JWT_ISSUER=Value (press Enter for default): "
    if "!INPUT_JWT_ISSUER!"=="" (
        set "JWT_ISSUER=https://dokus.local"
    ) else (
        set "JWT_ISSUER=!INPUT_JWT_ISSUER!"
    )

    REM JWT Audience
    echo.
    echo JWT audience:
    echo Default: dokus-api
    set /p "INPUT_JWT_AUDIENCE=Value (press Enter for default): "
    if "!INPUT_JWT_AUDIENCE!"=="" (
        set "JWT_AUDIENCE=dokus-api"
    ) else (
        set "JWT_AUDIENCE=!INPUT_JWT_AUDIENCE!"
    )

    REM Log Level
    echo.
    echo Log level:
    echo Default: INFO
    set /p "INPUT_LOG_LEVEL=Value (press Enter for default): "
    if "!INPUT_LOG_LEVEL!"=="" (
        set "LOG_LEVEL=INFO"
    ) else (
        set "LOG_LEVEL=!INPUT_LOG_LEVEL!"
    )

    REM Create .env file
    (
        echo # Dokus Environment Configuration
        echo # Generated on %date% %time%
        echo.
        echo # Database Configuration
        echo DB_USERNAME=!DB_USERNAME!
        echo DB_PASSWORD=!DB_PASSWORD!
        echo.
        echo # Redis Configuration
        echo REDIS_PASSWORD=!REDIS_PASSWORD!
        echo.
        echo # RabbitMQ Configuration
        echo RABBITMQ_USERNAME=!RABBITMQ_USERNAME!
        echo RABBITMQ_PASSWORD=!RABBITMQ_PASSWORD!
        echo.
        echo # JWT Configuration ^(Auth Service^)
        echo JWT_SECRET=!JWT_SECRET_FINAL!
        echo JWT_ISSUER=!JWT_ISSUER!
        echo JWT_AUDIENCE=!JWT_AUDIENCE!
        echo.
        echo # Logging
        echo LOG_LEVEL=!LOG_LEVEL!
    ) > .env

    echo.
    echo [+] Configuration saved to .env
    echo [!] Keep this file secure - it contains sensitive passwords

) else (
    echo [+] .env file exists
    echo.
    set /p RECONFIGURE="Would you like to reconfigure? (y/n): "
    if /i "!RECONFIGURE!"=="y" (
        echo [!] Backing up existing .env to .env.backup
        copy .env .env.backup >nul
        del .env
        call %0
        exit /b 0
    )
)
echo.

REM Configure Docker for insecure registry
echo [3/6] Configuring Docker registry...
echo.
echo [!] Please configure insecure registry in Docker Desktop:
echo   1. Open Docker Desktop
echo   2. Go to Settings -^> Docker Engine
echo   3. Add the following to the JSON config:
echo      "insecure-registries": ["94.111.226.82:5000"]
echo   4. Click 'Apply ^& Restart'
echo.
pause

REM Pull latest images
echo [4/6] Pulling latest Docker images...
echo This may take a few minutes...

docker compose pull
if %ERRORLEVEL% NEQ 0 (
    echo [X] Failed to pull images
    echo Check your internet connection and Docker registry configuration
    pause
    exit /b 1
)
echo [+] Images pulled successfully
echo.

REM Start services
echo [5/6] Starting Dokus services...

docker compose up -d
if %ERRORLEVEL% NEQ 0 (
    echo [X] Failed to start services
    pause
    exit /b 1
)
echo [+] Services started
echo.

REM Wait for services to be healthy
echo [6/6] Waiting for services to be ready...
echo This may take up to 2 minutes...

timeout /t 10 /nobreak >nul

set MAX_RETRIES=30
set RETRY_COUNT=0

:CHECK_HEALTH
docker compose ps | findstr /C:"healthy" >nul
if %ERRORLEVEL% EQU 0 (
    echo [+] Services are starting up...
)

set /a RETRY_COUNT+=1
if %RETRY_COUNT% GEQ %MAX_RETRIES% (
    echo [!] Some services may still be starting
    echo Run 'docker compose ps' to check service status
    goto AFTER_HEALTH
)

timeout /t 5 /nobreak >nul
goto CHECK_HEALTH

:AFTER_HEALTH
echo.

REM Configure auto-start
echo Configure Auto-Start
set /p AUTO_START="Would you like Dokus to start automatically with Docker Desktop? (y/n): "

if /i "!AUTO_START!"=="y" (
    REM For Windows, we rely on Docker Desktop's restart policy
    echo.
    echo [+] Auto-start is configured via Docker's restart policy
    echo Dokus will start automatically when Docker Desktop starts
    echo.
    echo To make Docker Desktop start on boot:
    echo   1. Open Docker Desktop Settings
    echo   2. Go to General
    echo   3. Enable "Start Docker Desktop when you log in"
) else (
    echo Skipping auto-start configuration
)

REM Display status
echo.
echo ============================================
echo [+] Dokus Server is running!
echo ============================================
echo.
echo Services available at:
echo   Auth Service:      http://localhost:6091
echo   Invoicing Service: http://localhost:6092
echo   Expense Service:   http://localhost:6093
echo   Payment Service:   http://localhost:6094
echo   Reporting Service: http://localhost:6095
echo   Audit Service:     http://localhost:6096
echo   Banking Service:   http://localhost:6097
echo.
echo   RabbitMQ UI:       http://localhost:15672
echo.
echo Useful commands:
echo   View logs:    docker compose logs -f
echo   Stop:         docker compose stop
echo   Restart:      docker compose restart
echo   Update:       docker compose pull ^&^& docker compose up -d
echo   Uninstall:    docker compose down -v
echo.
pause
