package tech.dokus.foundation.ktor.config

import com.typesafe.config.Config

/**
 * Configuration for object storage public URL.
 *
 * The publicUrl is used to rewrite presigned URLs generated by MinIO
 * so they're accessible from client apps (desktop, mobile, web).
 * Internal MinIO URLs (e.g., http://minio:9000/...) are replaced with
 * the public URL (e.g., https://app.dokus.tech/storage/...).
 */
data class StorageConfig(
    val publicUrl: String?
) {
    companion object {
        fun fromConfig(config: Config): StorageConfig = StorageConfig(
            publicUrl = if (config.hasPath("publicUrl")) {
                config.getString("publicUrl").takeIf { it.isNotBlank() }
            } else null
        )

        fun empty(): StorageConfig = StorageConfig(publicUrl = null)
    }
}
